Fixed an error when try to add a work under a collection
- Fixed NoMethodError: undefined method `add_members_by_ids' for Hyrax::Collections::CollectionMemberService:Class
- We overwrites collection_member_service to have list of sub collections sorted by sub collections title asc order but in 3.6.0 it's a different interface. collection_member_service is a wrapper of collection_member_search_service.
- Will need to figure how to sort sub-collection alphabetical order since it's not by default.